#!/usr/bin/env node
/**
 * Reads the repo-root `.env` (the single place you edit) and fans the values
 * out to the files each tool actually reads:
 *
 *   services/course-ls/.dev.vars   → GOOGLE_MAPS_API_KEY   (wrangler dev secret)
 *   apps/web/.env.local            → NEXT_PUBLIC_* URLs     (next dev / build)
 *
 * Cloudflare creds (CLOUDFLARE_API_TOKEN / _ACCOUNT_ID) are consumed straight
 * from the environment by `scripts/with-env.sh`, so they don't need a file.
 *
 * Run: pnpm env:sync
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");

if (!existsSync(envPath)) {
  console.error("✗ No .env at repo root. Run:  cp .env.example .env");
  process.exit(1);
}

/** @type {Record<string,string>} */
const env = {};
for (const line of readFileSync(envPath, "utf8").split("\n")) {
  const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
  if (m && !line.trimStart().startsWith("#")) {
    env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}

const files = {
  "services/course-ls/.dev.vars": [
    `GOOGLE_MAPS_API_KEY=${env.GOOGLE_MAPS_API_KEY ?? ""}`,
  ],
  "apps/web/.env.local": [
    `NEXT_PUBLIC_SYNC_ENDPOINT=${env.NEXT_PUBLIC_SYNC_ENDPOINT ?? "http://localhost:8787/api"}`,
    `NEXT_PUBLIC_COURSE_LS_ENDPOINT=${env.NEXT_PUBLIC_COURSE_LS_ENDPOINT ?? ""}`,
  ],
};

for (const [rel, lines] of Object.entries(files)) {
  writeFileSync(
    join(root, rel),
    `# Generated by \`pnpm env:sync\` from the repo-root .env — do not edit.\n${lines.join("\n")}\n`,
  );
  console.log("✓ wrote", rel);
}
